### ISSUE TITLE
"The template output 'Password' is not valid: The language expression property array index '1' is out of bounds.."

### ISSUE THREAD

**Issue by David-Pivotal** [pivotal-cf/docs-pcf-install#138] opened 2017-06-15 05:33 UTC
Hi,

Customer follows http://docs.pivotal.io/pivotalcf/1-8/customizing/pcf_azure.html and hit the following issue when install a basic, opinionated PCF on Azure using the Azure Marketplace. Is this a template bug?

`{"code":"DeploymentOutputEvaluationFailed","message":"Unable to evaluate template outputs: 'Password'. Please see error details and deployment operations. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"DeploymentOutputEvaluationFailed","target":"Password","message":"The template output 'Password' is not valid: The language expression property array index '1' is out of bounds.."}]}`

**Comment by bentarnoff** [comment] 2017-06-19 22:39
Thanks for bringing this to our attention, @David-Pivotal. @cwsteve2117 can you speak to this?

**Comment by cwsteve2117** [comment] 2017-06-20 14:29
@David-Pivotal can you provide more detail on what happens with the deployment? Does the Ops Manager VM get created, or is this in advance of any Azure resources getting created in the Resource Group you specify?

CC @danhigham

**Comment by David-Pivotal** [comment] 2017-06-23 01:15
@cwsteve2117 Thank you for your patience and following up with this issue. I have posted the questions to customer and am still waiting for his reply.
I will update here once get more details.

**Comment by samdai** [comment] 2017-06-26 06:39
I meet the same issue when I deploy Pivotal Cloud Foundry on Microsoft Azure product, the error is as below, also attached the operation details images
```
ERROR TYPE
Unable to evaluate template outputs: 'Password'. Please see error details and deployment operations. Please see https://aka.ms/arm-debug for usage details. (Code: DeploymentOutputEvaluationFailed)
ERROR DETAILS
The template output 'Password' is not valid: The language expression property array index '1' is out of bounds.(Code:DeploymentOutputEvaluationFailed, Target:Password)
<img width="1382" alt="operation_details2" src="https://user-images.githubusercontent.com/555169/27527239-4524c628-5a7d-11e7-9c28-88c55580047d.png">
<img width="1373" alt="operation_details1" src="https://user-images.githubusercontent.com/555169/27527240-452c369c-5a7d-11e7-82df-556cd1140fa4.png">


```

**Comment by cwsteve2117** [comment] 2017-06-26 19:31
@samdai your subscription needs to be on a "Pay-as-you-go" subscription with your ARM core quota increased to at least 100 cores. The actual runtime is closer to 50+ cores, but there are ephemeral VMs that do work during the install, hence needing a higher quota.

From what I've seen, I believe this issue related to insufficient core quota or incorrect subscription type. I'm unable to reproduce from my subscription.

**Comment by samdai** [comment] 2017-06-27 01:21
Thanks a lot.

**Comment by bentarnoff** [comment] 2017-06-28 16:26
Thanks for your help @cwsteve2117. Since both the "Pay-as-you-go" subscription and the increased ARM core quota are already documented in this topic, I am closing this issue.

**Closed by bentarnoff** 2017-06-28 16:26 UTC
Labels: unscheduled
